language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
after_success:
  - 'yarn travis-deploy-once "yarn semantic-release"'
  - 'yarn coveralls'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
